[package]
name = "daglight-simulation-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
daglight-protocol-block-perception.workspace = true
daglight-protocol-node.workspace = true
daglight-protocol-parameters.workspace = true
daglight-protocol-store.workspace = true
