use std::env::args;
use std::fs::write;
use std::path::PathBuf;

use daglight_visualisation_recorder::{Replay, Scenario};

/// Records every scenario and writes them as a script the player loads:
/// `daglight-recorder [path]`, by default `visualisation/player/replays.js`.
fn main() {
    let path = PathBuf::from(
        args()
            .nth(1)
            .unwrap_or_else(|| "visualisation/player/replays.js".to_string()),
    );
    let replays: Vec<String> = Scenario::all()
        .iter()
        .map(|scenario| {
            let replay = Replay::record(scenario);
            eprintln!(
                "{}: {} blocks, {} steps",
                scenario.id,
                replay.blocks.len(),
                replay.steps.len()
            );
            replay.json()
        })
        .collect();
    write(
        &path,
        format!(
            "// Generated by `daglight-recorder`; run visualisation/player/build.sh to regenerate.\nwindow.DAGLIGHT_REPLAYS = [{}];\n",
            replays.join(",\n")
        ),
    )
    .expect("the replays are written");
    eprintln!("wrote {}", path.display());
}
