[package]
name = "daglight-protocol-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
daglight-protocol-block.workspace = true
daglight-protocol-topology.workspace = true
daglight-protocol-block-perception.workspace = true
daglight-protocol-dag.workspace = true
daglight-protocol-parameters.workspace = true

[dev-dependencies]
